spring:
  profiles:
    active: prod

  # 파일 업로드 크기 제한 설정
  servlet:
    multipart:
      max-file-size: 10MB      # 개별 파일 최대 크기
      max-request-size: 20MB   # 전체 요청 최대 크기

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}

  output:
    ansi:
      enabled: always

  # Jackson 설정
  jackson:
    serialization:
      indent-output: true
    time-zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_VALIDITY}

server:
  tomcat:
    keep-alive-timeout: 60s
    max-keep-alive-requests: 100

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  cache:
    disabled: false  # 캐시 활성화
  enable-kotlin: true

discord:
  webhook:
    alarm:
      url: ${DISCORD_ALARM_WEBHOOK_URL}
    error-monitoring:
      url: ${DISCORD_ERROR_WEBHOOK_URL}

# Firebase 설정
firebase:
  web-api-key: ${FIREBASE_WEB_API_KEY}