# Local Development Profile (H2 Database)
spring:
  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:file:./data/duit;MODE=MySQL;AUTO_SERVER=TRUE
    #    username: sa
    #    password:

    # local mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${LOCAL_DB_PORT}/${DB_NAME}?rewriteBatchedStatements=true&allowLoadLocalInfile=true&useServerPrepStmts=false&cachePrepStmts=true&prepStmtCacheSize=500&prepStmtCacheSqlLimit=2048
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update  # 스키마 자동 업데이트 (데이터 유지)
    show-sql: true  # SQL 로그 출력 비활성화 (대량 데이터 처리 시 성능 향상)
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect

# 파일 스토리지 설정 (로컬)
file:
  upload-dir: C:/temp/duit-uploads
  base-url: http://localhost:8080
