global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'duit-server-blue'
    static_configs:
      - targets: ['duit-server-blue:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    labels:
      environment: 'blue'

  - job_name: 'duit-server-green'
    static_configs:
      - targets: ['duit-server-green:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    labels:
      environment: 'green'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']